### ISSUE TITLE
Runtime error 5

### ISSUE THREAD

**Issue by DavidXanatos** [csandker/InterProcessCommunication-Samples#1]
When I try the explicit samples the RPC call fails with error 5
I have set server to localhost so thats not it...

Also would you have a sample using ncalrpc ?

**Comment by csandker** [comment]
Did you specify the correct and matching host, protocol sequence and port (on both sides) ?
For the client you can find these explicit settings here: https://github.com/csandker/InterProcessCommunication-Samples/blob/master/RPC/CPP-RPC-Client-Server/RPC-Client1-Explicit-Auth-QOS/RPC-Client1-Explicit-Auth-QOS.cpp#L19-L43

For the server, these explicit settings can be found here: https://github.com/csandker/InterProcessCommunication-Samples/blob/master/RPC/CPP-RPC-Client-Server/RPC-Server1-Explicit-SecurityCallback-Auth/RPC-Server-Explicit-SecurityCallback-Auth.cpp#L85-L104
(There's also an ncalrpc option in this code block)

**Comment by DavidXanatos** [comment]
> Did you specify the correct and matching host, protocol sequence and port (on both sides) ?

I think so,

anyhow the sample you mentioned seams to be working thanks

**Comment by csandker** [comment]
Glad you have working code now.

For others running into the same error as you did: Can you let me know, which server you set up and which client you used to connect that caused the Access Denied Error (Error 5) to reproduce your initial problem?

**Comment by DavidXanatos** [comment]
Do you have an example of ncalrpc IPC that uses a dynamic endpoint?

**Comment by csandker** [comment]
There is this ncalrpc here: https://github.com/csandker/InterProcessCommunication-Samples/blob/master/RPC/CPP-RPC-Client-Server/RPC-Client1-Explicit-Auth-QOS/RPC-Client1-Explicit-Auth-QOS.cpp#L33-L37

```C++
          case LRPC:
		pszProtSeq = (RPC_WSTR)L"ncalrpc";
		pszTCPPort = (RPC_WSTR)L"\\RPC Control\\FRPC-LRPC";
		pszTCPHost = (RPC_WSTR)L"";	// for LRPC we're always connect to a local RPC endpoint. If you add something here your might get error '1707'
		pszHostSPN = (RPC_WSTR)L"LocalAdm"; // NEEDS ADJUSTMENT -- For LRPC set the user that runs the RPC endpoint here, this is a dummy value
		break;
```

Apart from that there is nothing I can pass on for now.

Do you mind passing the details that resulted in your initial error condition so that i can reproduce and if necessary update the samples?
