### ISSUE TITLE
CPP-Basic-PipeClient.cpp - connect to pipe without prefix

### ISSUE THREAD

**Issue by 1lyasam** [csandker/InterProcessCommunication-Samples#2]
Hi Carsten, thanks for the great article you wrote. taught me a lot !
It seems that there is a bug in "CPP-Basic-PipeClient.cpp". 
it tries to connect to a server with the pipe name from the input but without the prefix of  -  L"\\\\.\\pipe\\"

https://github.com/csandker/InterProcessCommunication-Samples/blob/b7e60a5891501278536fe7f2de742ea231dea8bf/NamedPipes/CPP-NamedPipe-Basic-Client-Server/CPP-Basic-PipeClient/CPP-Basic-PipeClient.cpp#L58

**Comment by csandker** [comment]
Hi @1lyasam,

thanks for raising this. I believe initially there was some good intention to make it this way, but you're right it is inconsistent with the server and could confuse people. Fixed it in cf4773ccf6ad5f6971177b180db9c3939da33c05.

![image](https://user-images.githubusercontent.com/4909972/151653292-867f8a3f-63c7-453a-b691-58ab923f2e36.png)

Also - not to be mentioned last - thanks for your kind introduction :)
