### ISSUE TITLE
Problem on the server contacts the client

### ISSUE THREAD

**Issue by HigreenMolly** [csandker/InterProcessCommunication-Samples#6]

**Comment by HigreenMolly** [comment]
Hi Carsten, thanks for your article about ALPC, learn a lot of things. 

I still have questions about the use of connection and communication ports. As your description, the server have the connection port as an entrance for all the communication ports, and the system will help us to pick the specific client's communication port.

When i test your demo, the client can send message to server any time, and the server can reply the message for client successfully. But when i use my server send message to client actively, it was denied. 

I guess the root cause was the communication ports i picked, when i reply the message from client, i filled the messageid by client's messageid and reply it by connection port, the system can find the right communication port by messageid. But when i contact client actively, maybe the system couldn't find the way.

I didn't find the related info on the msg header, how i fix this problem.

**Comment by csandker** [comment]
Hi there,

sorry for the delay in coming back to you. Is the issue this relevant to you? If so could your please provide your code that is failing with an access denied?
Fair warning: It might take me - once again - a while to get back to you due to other projects and vacations.

Cheers
